ALTER TABLE videos ADD COLUMN IF NOT EXISTS md5 VARCHAR(32);
ALTER TABLE videos ADD COLUMN IF NOT EXISTS upload_id VARCHAR(200);
ALTER TABLE videos ADD COLUMN IF NOT EXISTS part_size BIGINT;

CREATE INDEX IF NOT EXISTS idx_videos_md5 ON videos (md5);
